import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { HydrationContext , Client } from "react-hydration-provider";
// import { Providers} from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UPTUZ - OFFICIAL",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  }
}

export default function RootLayout({
  children,
  params: {locale},
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>
        {/* <Providers> */}
        <Navbar />
        {children}
        {/* </Providers> */}
      </body>
    </html>
  );
}
